version: 2
updates:
- package-ecosystem: pip
  directory: "/tests"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
    - 21.4.2
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: docker
  directory: "/tests"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - 3.9.3
  commit-message:
    prefix: chore
    include: scope
