name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install gitlint
        run: pip install gitlint
      - name: Run gitlint
        run: git log && gitlint --contrib contrib-title-conventional-commits --ignore B6 --commits ${GITHUB_REF}..HEAD lint
